// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eilgptvbqczpfgmojnvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbGdwdHZicWN6cGZnbW9qbnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjAwNDMsImV4cCI6MjA2OTk5NjA0M30.0Eyzg_OH3QnMOrUVB07Z0Ai6K9234O-kMot_N77eo4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});